version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: tg_bot_redis
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
# docker exec -it tg_bot_redis sh
# redis-cli -a "test"
# KEYS *
# LRANGE chat_history:800465831 0 -1
