# .github/workflows/deploy.yml
name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/tg-bot-app cmd/main.go

      - name: Create .env from secrets
        run: |
          echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" >> .env
          echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> .env
          echo "REDIS_ADDR=${{ secrets.REDIS_ADDR }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.VPS_HOST }} ssh-ed25519 ..." >> ~/.ssh/known_hosts

      - name: Deploy files
        run: |
          # Создаем целевую директорию если ее нет
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "mkdir -p /home/${{ secrets.VPS_USER }}/tg-bot-app"

          # Копируем бинарник и .env
          scp -i ~/.ssh/id_ed25519 bin/tg-bot-app .env \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/tg-bot-app/

          # Даем права на исполнение
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "chmod +x /home/${{ secrets.VPS_USER }}/tg-bot-app/tg-bot-app"

      - name: Restart service
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "systemctl --user restart telegram-bot-go.service || sudo systemctl restart telegram-bot-go.service"
