name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o bin/tg-bot-app cmd/tg-bot-app/main.go # Изменил имя бинарника

      - name: Create .env file from secrets
        run: |
          echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" > .env  # Использую > вместо >> чтобы перезаписать
          echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> .env
          echo "REDIS_ADDR=${{ secrets.REDIS_ADDR }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files
        run: |
          # Создаем целевую и временную директории, если их нет
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /home/admin2/tg-bot-app/tmp"

          # Копируем бинарник и .env во временную директорию
          scp bin/tg-bot-app .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/admin2/tg-bot-app/tmp/

          # Останавливаем сервис перед заменой файлов
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo systemctl stop telegram-bot-go.service"

          # Перемещаем новые файлы из временной директории и удаляем tmp
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "\
          mv /home/admin2/tg-bot-app/tmp/tg-bot-app /home/admin2/tg-bot-app/tg-bot-app && \
          mv /home/admin2/tg-bot-app/tmp/.env /home/admin2/tg-bot-app/.env && \
          rm -rf /home/admin2/tg-bot-app/tmp"

          # Даем права на исполнение
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "chmod +x /home/admin2/tg-bot-app/tg-bot-app"

      - name: Restart service
        run: |
          # Перезапускаем systemd сервис
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo systemctl start telegram-bot-go.service"
