name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o bin/tg-bot-app cmd/tg-bot-app/main.go

      - name: Create .env file
        run: |
          echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" > .env
          echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> .env
          echo "REDIS_ADDR=${{ secrets.REDIS_ADDR }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.VPS_HOST }} $(ssh-keyscan -H ${{ secrets.VPS_HOST }})" >> ~/.ssh/known_hosts

      - name: Deploy files
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            mkdir -p /home/admin2/tg-bot-app
            echo "${{ secrets.REDIS_PASSWORD }}" | sudo -S systemctl stop telegram-bot-go.service || true
          EOF
          scp bin/tg-bot-app .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/admin2/tg-bot-app/

      - name: Restart service
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            chmod +x /home/admin2/tg-bot-app/tg-bot-app
            echo "${{ secrets.REDIS_PASSWORD }}" | sudo -S systemctl restart telegram-bot-go.service
            sleep 5
            sudo systemctl status telegram-bot-go.service
          EOF
